# docker/docker-compose.yaml
version: '3.8'

services:
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - wp_network
    restart: unless-stopped

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:ro
    environment:
      - AWS_DEFAULT_REGION=eu-west-3
    networks:
      - wp_network
    restart: unless-stopped

volumes:
  wordpress:
  letsencrypt:

networks:
  wp_network:
    driver: bridge