# docker/docker-compose.yaml
version: '3'

services:
  wordpress:
    image: ${ECR_REGISTRY}/wordpress-app:preprod
    volumes:
      - wp_data:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - wp_network

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    restart: always
    networks:
      - wp_network

networks:
  wp_network:

volumes:
  wp_data: