name: Build and Push Docker Images

on:
  push:
    branches: [ images-docker ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-pipeline.yml'

env:
  AWS_REGION: eu-west-3
  REGISTRY: 730335289383.dkr.ecr.eu-west-3.amazonaws.com
  WORDPRESS_REPOSITORY: wordpress-app
  NGINX_REPOSITORY: nginx
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Extract metadata
        id: meta
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build and push WordPress image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:latest
            ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}
            ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:${{ env.VERSION }}-${{ steps.meta.outputs.date }}

      - name: Pull and push Nginx image
        run: |
          # Pull Nginx
          docker pull nginx:1.24-alpine
          
          # Tag with multiple tags
          docker tag nginx:1.24-alpine ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:1.24-alpine
          docker tag nginx:1.24-alpine ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}
          docker tag nginx:1.24-alpine ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ env.VERSION }}-${{ steps.meta.outputs.date }}
          
          # Push all tags
          docker push ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:1.24-alpine
          docker push ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}
          docker push ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ env.VERSION }}-${{ steps.meta.outputs.date }}

      - name: Update docker-compose.yaml with new tags
        run: |
          sed -i "s|image: nginx:.*|image: ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}|" docker/docker-compose.yaml
          sed -i "s|image: ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:.*|image: ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}|" docker/docker-compose.yaml

      - name: Display image information
        run: |
          echo "Built and pushed the following images:"
          echo ""
          echo "WordPress images:"
          echo "- ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:latest"
          echo "- ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}"
          echo "- ${{ env.REGISTRY }}/${{ env.WORDPRESS_REPOSITORY }}:${{ env.VERSION }}-${{ steps.meta.outputs.date }}"
          echo ""
          echo "Nginx images:"
          echo "- ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:1.24-alpine"
          echo "- ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ steps.meta.outputs.sha_short }}"
          echo "- ${{ env.REGISTRY }}/${{ env.NGINX_REPOSITORY }}:${{ env.VERSION }}-${{ steps.meta.outputs.date }}"