name: Deploy to Preprod

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '**.md'

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: wordpress-app
  DOCKER_DIR: docker
  GITHUB_REPO: "https://github.com/mmmustar/mmustar.fr.git"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get EC2 Host
        id: get-host
        run: |
          EC2_HOST=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=preprod-instance" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "ec2_host=$EC2_HOST" >> $GITHUB_OUTPUT
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push WordPress image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.DOCKER_DIR }}
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:preprod
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      
      - name: Deploy to EC2
        if: steps.get-host.outputs.ec2_host != ''
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.get-host.outputs.ec2_host }}
          username: ec2-user
          key: ${{ secrets.EC2_PREPROD_SSH_KEY }}
          script: |
            rm -rf ~/wordpress-preprod
            mkdir -p ~/wordpress-preprod
            cd ~/wordpress-preprod
            
            git clone ${{ env.GITHUB_REPO }} .
            
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            
            cd ${{ env.DOCKER_DIR }}
            sed -i "s|ECR_REGISTRY=.*|ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}|g" .env
            
            docker compose pull
            docker compose down --volumes
            docker compose up -d
            
            docker image prune -f
      
      - name: Verify deployment
        if: steps.get-host.outputs.ec2_host != ''
        run: |
          sleep 30
          curl -f http://${{ steps.get-host.outputs.ec2_host }} || exit 1